server {
    listen 80;
    server_name localhost;

    # Tudo que começar com /api vai para o Spring
    location /api {
        proxy_pass http://app:8080;
    }

    # Todo o resto vai para o Next.js
    location / {
        proxy_pass http://web:3000;
    }
}