# Configurações de Desenvolvimento - Steam Card
spring.application.name=steamcard
server.servlet.context-path=/api

# Configurações do Redis (conectando ao container 'redis' do docker compose)
spring.data.redis.host=redis
spring.data.redis.port=6379

# Configurações do Spring DevTools para Hot Reloading
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.livereload.enabled=true

# Níveis de Logs para ajudar no desenvolvimento
logging.level.org.springframework.web=INFO
logging.level.com.mello.steamcard=DEBUG
